### ISSUE TITLE
roblox crushing in starting game

### ISSUE THREAD

**Issue by druemae** [vinegarhq/sober#305] opened 2024-10-11 07:03 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

help please roblox crashes when i launch the game what to do?

**Comment by skoove** [comment] 2024-10-11 07:30
why did you make another issue, check for duplicates next time, it even tells you to

**Comment by apprehensions** [comment] 2024-10-11 07:32
No logs, no details given. Most likely a duplicate of #302

**Closed by apprehensions** 2024-10-11 07:32 UTC
Labels: bug
