### ISSUE TITLE
Multi-instance support

### ISSUE THREAD

**Issue by AppliedPlumbing2** [vinegarhq/sober#30] opened 2024-08-05 01:29 UTC
### Before Creating the Enhancement Request

- [x] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

I like to play tower defense games on roblox with multiple accounts at the same time

### Describe the Solution you'd Like

Ability to open and play multiple roblox clients at the same time

I know this is a sort of gray area in the rules, but vinegar also had support for it as long as you went into the settings and enabled it

### Describe Alternatives you've considered

I noticed I could open more than one window, but all of the instances seem to fall apart when i log out of one of them and try to add in a separate account

i wouldn't know how else to do this except for sandboxing (too dumb to do that) or virtual machines (i only have one gpu)

**Comment by TeknosQuet** [comment] 2024-08-05 11:46
Multi-instance gameplay is considered malicious according to Roblox staff, so I wouldn't expect Sober to support it.
![image](https://github.com/user-attachments/assets/db0dd21f-d2c6-43e4-93d0-5c104b7d5d6a)
It does reference the Windows client but I assume it would (and should) apply the same way to Sober and any other client on any other platform.

**Comment by xunuwu** [comment] 2024-08-05 16:51
> Multi-instance gameplay is considered malicious according to Roblox staff, so I wouldn't expect Sober to support it.
> 
> https://devforum.roblox.com/t/do-something-with-x32-clients/2318875/126 ![image](https://private-user-images.githubusercontent.com/40285364/355089216-db0dd21f-d2c6-43e4-93d0-5c104b7d5d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzY3MTMsIm5iZiI6MTcyMjg3NjQxMywicGF0aCI6Ii80MDI4NTM2NC8zNTUwODkyMTYtZGIwZGQyMWYtZDJjNi00M2U0LTkzZDAtNWMxMDRiN2Q1ZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE2NDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDE0N2UzMjJhOTU1YzY0ZmY5M2M1ZTQ5OGVjNGVkYTVkZWRkMzEyZmI4MzRhOGI4MDFlOTFmOGJlNDVhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LoA-t0lh8sywJiQuoVPuGL0g7ZGu87yDlHDHmYGshbE)
> 
> It does reference the Windows client but I assume it would (and should) apply the same way to Sober and any other client on any other platform.

Hyperion doesn't seem to block it on windows, just closing the ROBLOX_singletonEvent handle in process hacker is enough to open multiple instances, just like it was pre-hyperion.
![image](https://github.com/user-attachments/assets/2d4339a3-2cad-4043-91dd-c5271051d23a)

Also, sober already supports multiple instances, the problem is that it doesn't automatically login to the account you are logged in to in the browser, so you have to manually switch accounts in-app every time which is a bit of a hassle. I would like to see a feature that made switching accounts easier.
![image](https://github.com/user-attachments/assets/35334827-03f4-4e9d-9e43-a05ac330ddc1)

**Comment by AppliedPlumbing2** [comment] 2024-08-05 18:36
> > Multi-instance gameplay is considered malicious according to Roblox staff, so I wouldn't expect Sober to support it.
> > https://devforum.roblox.com/t/do-something-with-x32-clients/2318875/126 ![image](https://private-user-images.githubusercontent.com/40285364/355089216-db0dd21f-d2c6-43e4-93d0-5c104b7d5d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzY3MTMsIm5iZiI6MTcyMjg3NjQxMywicGF0aCI6Ii80MDI4NTM2NC8zNTUwODkyMTYtZGIwZGQyMWYtZDJjNi00M2U0LTkzZDAtNWMxMDRiN2Q1ZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE2NDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDE0N2UzMjJhOTU1YzY0ZmY5M2M1ZTQ5OGVjNGVkYTVkZWRkMzEyZmI4MzRhOGI4MDFlOTFmOGJlNDVhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LoA-t0lh8sywJiQuoVPuGL0g7ZGu87yDlHDHmYGshbE)
> > It does reference the Windows client but I assume it would (and should) apply the same way to Sober and any other client on any other platform.
> 
> Hyperion doesn't seem to block it on windows, just closing the ROBLOX_singletonEvent handle in process hacker is enough to open multiple instances, just like it was pre-hyperion. ![image](https://private-user-images.githubusercontent.com/73060771/355177993-2d4339a3-2cad-4043-91dd-c5271051d23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODIwOTMsIm5iZiI6MTcyMjg4MTc5MywicGF0aCI6Ii83MzA2MDc3MS8zNTUxNzc5OTMtMmQ0MzM5YTMtMmNhZC00MDQzLTkxZGQtYzUyNzEwNTFkMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE4MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZWQxZTUxNDY1ZmE4OWEzZDJjMTliNTJmYjcxNjg0NDllNmI5NzM3NDAyOTlkN2QyMzcxZmY1ZWFhNjkyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-MdGzYody9TJhwou3M6jye9seyIvjrq6gjxHd63UWFg)
> 
> Also, sober already supports multiple instances, the problem is that it doesn't automatically login to the account you are logged in to in the browser, so you have to manually switch accounts in-app every time which is a bit of a hassle. I would like to see a feature that made switching accounts easier. ![image](https://private-user-images.githubusercontent.com/73060771/355180485-35334827-03f4-4e9d-9e43-a05ac330ddc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODIwOTMsIm5iZiI6MTcyMjg4MTc5MywicGF0aCI6Ii83MzA2MDc3MS8zNTUxODA0ODUtMzUzMzQ4MjctMDNmNC00ZTlkLTllNDMtYTA1YWMzMzBkZGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE4MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTE2ZDA1OTUwMGQ1MjY0ZjI0YWU1MzhkZGU1MGY4OGQxOGI3ZDRmYzZjNDY4MmRkM2RhMThmYzg2NDVlNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xC2P7eoYCTUds9mBFvw8oxH8Cv_dHI7rhLyAJCRWThY)

Okay so holy heck thank you for telling me this

I noticed sober had an update in flatpak and now i can actually do it now!!! idk why the older version wouldnt allow this

**Comment by apprehensions** [comment] 2024-08-05 18:37
Having this as a feature is yet to be decided, as Bitdancer stated that multi-instance support shouldn't be a feature.

**Comment by AppliedPlumbing2** [comment] 2024-08-05 18:40
> Having this as a feature is yet to be decided, as Bitdancer stated that multi-instance support shouldn't be a feature.

wait im confused
so like was it already a thing or is some weird linux fuckery letting us run multiple clients

**Comment by TeknosQuet** [comment] 2024-08-05 19:32
> Hyperion doesn't seem to block it on windows, just closing the ROBLOX_singletonEvent handle in process hacker is enough to open multiple instances, just like it was pre-hyperion.

It may have been a typo or misunderstanding, but I still believe there should be at least some clarification to know if this is explicitly allowed or not. I don't think Roblox goes out of their way to ban people who do this, but it can still potentially be used in a bad manner (eg. grinding a game on multiple accounts); I suppose what someone considers bad would be subjective though.

Personally, I would not want Sober to be on Roblox's bad side considering how new this project is and the history RoL as a whole. Adding a feature like this when it's not 100% clear if its allowed or not doesn't help.

**Comment by tunis4** [comment] 2024-11-30 23:00
will not be supported

**Closed by tunis4** 2024-11-30 23:00 UTC
Labels: enhancement

**Comment by Schweeeeeeeeeeeeeeee** [comment] 2025-06-30 15:50
it shouldnt be a feature but you are actively blocking it it worked before by having multiple flatpak save locations 😢
