### ISSUE TITLE
Audio cuts out a few seconds into an experience

### ISSUE THREAD

**Issue by IcicleTheWeavile** [vinegarhq/sober#106] opened 2024-08-14 09:46 UTC
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Nvidia 1070ti, KDE Neon, X11] As explained by the title, the in-game audio stops being played a few seconds after joining an experience. There's really not much to be said here other than exactly that.

### UPDATE

The newest update of Sober as of 27/08/2024, using the 2.693.688 APK bundle, this is a non-issue. I hereby declare this issue to be fixed!

### RE-UPDATE

(29/08/2024) Upon further inspection, the bug is not fixed. It seems as if the session I had was anomalous in its functioning audio. The issue is _not_ fixed, and help regarding it is still welcome!

**Comment by PanIntegralus** [comment] 2024-08-14 13:21
Does this happen on any experience? Can you share any info on your audio setup? Any logs?

**Comment by IcicleTheWeavile** [comment] 2024-08-14 17:35
> Does this happen on every experience? Can you share any info on your audio setup? Any logs?

It happens on every experience, yes. The headset I'm using is a OneOdio Pro 10, but as it works fine in every other game or app I use, I doubt the problems come from that. As for logs, no, I don't have any - but I would appreciate it if you could tell me where to find them. Thanks!

**Comment by PanIntegralus** [comment] 2024-08-14 18:45
If you have Pipewire, try using qpwgraph to check if the game audio is correctly router to your headset. Also, try running Sober through terminal to see if the app reports any errors.

**Comment by IcicleTheWeavile** [comment] 2024-08-14 19:28
Here's the result that both of these measures had!

1. In qpwgraph, the game audio was still correctly routed to my headset when it completely stopped outputting audio. There's no lack of connection between the app and my headset, so I assume this means that the issue is completely due to Sober itself.
2.  The only line in the terminal I could find regarding Audio was the following:

`[log @ Roblox]: 2024-08-14T19:25:43.606Z,5.606791,4ec006c0,6 [FLog::Audio] InputDevice 0: Android audio output({{ffffffff-ffff-ffff-ffffffffffffffff}}) 48000/2/4`

**Comment by Steammoch** [comment] 2024-08-18 03:41
Same happens to me, I'm using Zorin OS and tried running Sober with qpwgraph and it seemed to work perfectly fine

**Comment by roads51** [comment] 2024-08-20 17:12
same, it also seems to be connected to another problem where it can't load the roblox homepage when you leave the game because when i refresh the audio in settings it fixes it until it breaks again

**Comment by Steammoch** [comment] 2024-08-20 18:05
It doesn't do that to me, so it could be 2 separate issues with the same result

**Comment by IcicleTheWeavile** [comment] 2024-08-20 18:17
> _same, it also seems to be connected to another problem where it can't load the roblox homepage when you leave the game because when i refresh the audio in settings it fixes it until it breaks again_
> 
> i fixed it when i deleted the two sober remotes i had

If I can ask, what is and how can one delete the two Sober remotes? Since this seems to be correlated to my own problem. I'd love a fix.

**Comment by roads51** [comment] 2024-08-20 19:33
flatpak remotes for the list
flatpak remote-delete to delete them

**Comment by Steammoch** [comment] 2024-08-22 02:57
this didn't fix my problem at all, just uninstalled Sober

**Comment by IcicleTheWeavile** [comment] 2024-08-27 13:01
### UPDATE

The newest update of Sober as of 27/08/2024, using the 2.693.688 APK bundle, this is a non-issue. I hereby declare this issue to be fixed!

**Comment by IcicleTheWeavile** [comment] 2024-08-29 10:19
### RE-UPDATE

(29/08/2024) Upon further inspection, the bug is not fixed. It seems as if the session I had was anomalous in its functioning audio. The issue is _not_ fixed, and help regarding it is still welcome!

**Comment by Steammoch** [comment] 2024-08-30 20:47
still doesn't work for me, I have no idea why

**Comment by roads51** [comment] 2024-08-31 17:34
for me it broke again as soon as i updated it

**Comment by IcicleTheWeavile** [comment] 2024-09-06 21:55
A further update, while playing today, the audio off as normal, there was a small, 15 second or so window where I could hear the game audio again before it was taken from me. I was typing during that moment. I have no further information on this occurrence.

**Comment by IcicleTheWeavile** [comment] 2024-09-07 20:21
07/09/2024, I'm currently having a session wherein the audio works fine for seemingly no reason.

**Comment by IcicleTheWeavile** [comment] 2024-09-09 16:45
09/09/2024, the audio cutting is getting less and less consistent, I've learned that it seems to almost only ever happen when you join via the big green button as opposed to joining a server manually through the "join friends" feature. I've also noticed something I mistook for normal earlier - every time I exited an experience or closed the app, it would turn into a zombie process. Now I know that this only happens when the aforementioned audio cut occurs, so I can only assume that the two errors are related.

**Comment by PanIntegralus** [comment] 2024-09-10 02:06
I love seeing the progress of this issue and that it gets more and more fixed after every update lol

**Comment by IcicleTheWeavile** [comment] 2024-09-11 15:34
11/09/24, upon further inspection I can conclude that the switch between the source names "Sober" and "SDL Application-1 [Audio Stream]" isn't tied to the audio cutting out. A reinspection found that the source's name now remains as "Sober" even after the audio cuts out, leaving me a big confused as to why this seemed to be the case a few days ago. I attempted to close any other apps that were producing audio in the background and then launch sober to see if it was some kind of intermission but this doesn't seem to be the case. I'm working to try and find a way to replicate the functional audio sessions in a consistent manner.

**Comment by IcicleTheWeavile** [comment] 2024-09-16 14:58
16/09/24, the new update didn't seem to affect this issue in any way. I have noticed better performance but still no consistent audio.

**Comment by IcicleTheWeavile** [comment] 2024-09-22 17:12
22/09/24, i'm currently running very frequent non-audio cutting sessions, what do you guys recommend i do to diagnose the environment and try to guarantee this state every session?

**Comment by V3L0C1T13S** [comment] 2024-09-22 19:08
> 22/09/24, i'm currently running very frequent non-audio cutting sessions, what do you guys recommend i do to diagnose the environment and try to guarantee this state every session?

For now, you can try putting your system under stress while Sober is running, such as by running another demanding game in the background. It would also be helpful if you attach the last few parts of your `dmesg` if you manage to reproduce this issue again.

**Comment by IcicleTheWeavile** [comment] 2024-09-23 06:07
Sounds good, the only thing I'd like is some more closure - how do I access the dsmeg? You said you want the last few parts when I manage to reproduce the issue, as in, when the audio does cut? Do I need to recover the lines immediately after the audio stops? Thanks.

**Comment by V3L0C1T13S** [comment] 2024-09-23 14:25
> Sounds good, the only thing I'd like is some more closure - how do I access the dsmeg? You said you want the last few parts when I manage to reproduce the issue, as in, when the audio does cut? Do I need to recover the lines immediately after the audio stops? Thanks.

You can access the dmesg by running the command `sudo dmesg`. And yes, I'd like the last few parts after the audio cuts. Dmesg should have a counter before each message, which you can use to find logs that happened recently.

**Comment by IcicleTheWeavile** [comment] 2024-09-23 16:25
> You can access the dmesg by running the command `sudo dmesg`. And yes, I'd like the last few parts after the audio cuts. Dmesg should have a counter before each message, which you can use to find logs that happened recently.

Here is the last 5 lines of dmesg as the audio cut!

```
[ 6640.561003] audit: type=1400 audit(1727108567.031:993): apparmor="DENIED" operation="open" class="file" profile="firefox" name="/proc/5469/oom_score_adj" pid=5358 comm="firefox" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
[ 6641.122648] audit: type=1400 audit(1727108567.592:994): apparmor="DENIED" operation="open" class="file" profile="firefox" name="/proc/5469/oom_score_adj" pid=5358 comm="firefox" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
[ 6641.457529] audit: type=1400 audit(1727108567.927:995): apparmor="DENIED" operation="open" class="file" profile="firefox" name="/proc/13865/oom_score_adj" pid=5358 comm="firefox" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
[ 6642.484404] audit: type=1400 audit(1727108568.954:996): apparmor="DENIED" operation="open" class="file" profile="firefox" name="/proc/13865/oom_score_adj" pid=5358 comm="firefox" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
[ 6642.754309] audit: type=1400 audit(1727108569.224:997): apparmor="DENIED" operation="open" class="file" profile="firefox" name="/proc/5469/oom_score_adj" pid=5358 comm="firefox" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000

```

**Comment by Andy-Danderson** [comment] 2024-09-28 10:47
Hm, what version of the app have you been using? It seems that my game audio cuts out after about 10 seconds every session.

**Comment by IcicleTheWeavile** [comment] 2024-09-28 13:23
I'm using version 0.0.0-dc504d6!

**Comment by Steammoch** [comment] 2024-09-29 17:58
for some reason now it just works for me? i have no idea why. only change is that i removed sober from my dashboard (i use zorin os)

**Comment by Steammoch** [comment] 2024-09-30 03:37
ok, nvm, it only seems to be working sometimes. i'd say 2 times out of 10

**Comment by IcicleTheWeavile** [comment] 2024-09-30 05:17
2 times out of 10 is precisely how I'd describe it! Keep us updated if you can offer any intel on the issue. I'll change GPU around Christmas, so I'll relay if that changes or fixes the issue in any way.

**Comment by Steammoch** [comment] 2024-09-30 11:40
It seems to sometimes be working better, like earlier today I could get working audio even after restarting it for a couple of times, but then after trying again later it didn't work anymore. Really weird

**Comment by Overlord30** [comment] 2024-10-01 01:40
I have a solution that worked for me 
I deleted all the sound files in `/home/MACHINENAME/.var/app/org.vinegarhq.Sober/cache/sober/sounds`
before joining a new experience.

**Comment by IcicleTheWeavile** [comment] 2024-10-01 05:06
I'm in the midst of distro-hopping, so I currently cannot perform any tests, but I will attempt that, as soon as I can, thank you!

**Comment by brilokuloj** [comment] 2024-10-01 14:10
I'm having the same issue. I tried deleting the sound cache and it still happens.

Mine is usually accompanied by an error like this:
`2024-10-01T14:06:24.698Z,38.698475,4f5576c0,6 [FLog::Error] Error: Failed to load sound rbxassetid://1492382312: Temp read failed.`

**Comment by IcicleTheWeavile** [comment] 2024-10-01 19:28
01/10/2024

HUZZAH! I switched to Fedora and, wouldn't you know it, this _might_ be a non-issue! I haven't ran extensive tests, but for the current sessions it seems like the audio works flawlessly. This issue will still be open, however, until the bug is fixed for not only me, but everyone else as well.

**Comment by Steammoch** [comment] 2024-11-16 16:42
This bug seems to be completly fixed as of now - I still have no idea why but I'm not complaining

**Comment by IcicleTheWeavile** [comment] 2024-11-16 16:51
Very good news! If in 3 days there are no more reports of this bug, I will go on and close it.

**Closed** 2024-11-21 22:01 UTC
Labels: bug
