### ISSUE TITLE
Sober not opening, no logs.

### ISSUE THREAD

**Issue by beamereater** [vinegarhq/sober#523] opened 2024-12-14 15:30 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried opening sober. Nothing happened. From the terminal, even in verbose mode, it shows nothing. No logs.

Running `flatpak -v run org.vinegarhq.Sober` I get the following output:
```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Skipping parental controls check for app/org.vinegarhq.Sober/x86_64/master since parental controls are disabled globally
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: /home/user/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/47/06c7c4463b7ee8ef28c508d9be695e92d8fc1f25957ef1bd891cd7d0da5e17da/files/lib32 does not exist
F: Allocated instance id 3612411647
F: Add defaults in dir /org/vinegarhq/Sober/
F: Add locks in dir /org/vinegarhq/Sober/
F: Allowing host-fs access
F: Not sharing "/run/media" with sandbox: Unable to open path "/run/media": No such file or directory
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Allowing session-dbus access
F: Allowing system-dbus access
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running 'bwrap --args 39 -- xdg-dbus-proxy --args=41'
F: Running 'bwrap --args 39 -- sober'
```
A short few seconds later, according to running `flatpak ps` a few times, it shows that Sober only runs for a couple of moments and closes.

Running `doas dmesg | grep sober` I get the following output:
```
[ 1327.137164] traps: sober[7004] trap invalid opcode ip:6445ac26b37f sp:7ffd13e8bf28 error:0 in sober[f037f,6445ac25d000+436000]
[ 1330.726506] traps: sober[7016] trap invalid opcode ip:56915abd837f sp:7ffe31cbb558 error:0 in sober[f037f,56915abca000+436000]
```
It appears that Sober tries to run code that isn't supported by my CPU? ROBLOX works fine on Windows, but I hate having to dual boot. Anything useful to help me get Sober working?

Specs:
OS: Artix Linux x86_64 (Also tested on Arch Linux x86_64 with the same output)
RAM: 4GB DDR3-1333
CPU: AMD Athlon II 635 (4 cores @ 2.9GHz)
GPU: ATI Radeon HD 5770 (1GB VRAM, 0.8GHz)
HDD: 512GB HDD
CPU Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save

**Comment by apprehensions** [comment] 2024-12-14 15:31
Duplicate of #94

**Closed by apprehensions** 2024-12-14 15:31 UTC
Labels: bug

**Comment by tunis4** [comment] 2024-12-14 16:39
your cpu is too old. android roblox requires at least SSE 4.2 support as it is specified in the android x86_64 abi. there is no fix other than getting a newer cpu.
