### ISSUE TITLE
crashes when try play a game

### ISSUE THREAD

**Issue by Nickng1233** [vinegarhq/sober#303] opened 2024-10-11 02:23 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

ever time i try to play a game using sober it crashes
i don't no what i'm do in wrong

**Comment by TheoW03** [comment] 2024-10-11 02:28
I have this same issue Idk T-T

**Comment by Nickng1233** [comment] 2024-10-11 02:38
don"t mind my bad grammer

**Comment by Nickng1233** [comment] 2024-10-11 02:41
don't mind my bad grammer
i don't know much english

**Comment by TheoW03** [comment] 2024-10-11 02:44
https://github.com/vinegarhq/sober/issues/302

im going to give attention to this thread btw

**Comment by Nickng1233** [comment] 2024-10-11 03:14
okay

**Comment by quuinnn** [comment] 2024-10-11 03:43
same issue here

**Comment by quuinnn** [comment] 2024-10-11 05:06
fixed it using this https://github.com/vinegarhq/sober/issues/302

**Comment by akshath197** [comment] 2024-10-11 05:41
I also have same issue. I dont know what to do.

**Comment by zverxy** [comment] 2024-10-11 05:43
+

**Comment by zverxy** [comment] 2024-10-11 05:44
as well

**Comment by OstapTelychko** [comment] 2024-10-11 06:51
Solution is in #302

**Comment by apprehensions** [comment] 2024-10-11 07:33
Duplicate of #297

**Closed by apprehensions** 2024-10-11 07:33 UTC
Labels: bug
