### ISSUE TITLE
Sober crashing in literally EVERY GAME that i join

### ISSUE THREAD

**Issue by MatTrof** [vinegarhq/sober#307] opened 2024-10-11 09:47 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

https://github.com/user-attachments/assets/8744437e-5b61-49fb-a52e-d86d440eb47b

I'm having a problem with joining any game in sober. I really dont know what to say other than that...

Linux version: 
Ubuntu 24.04.1 LTS

GPU: NVIDIA Geforce RTX 3070

```2024-10-11T09:40:52.576Z,0.576901,3096b340,6 [FLog::AndroidGLView] nativeInitClientSettings
2024-10-11T09:40:52.585Z,0.585835,3096b340,6 [FLog::Output] LoadClientSettingsFromLocal: "{
    "DFFlagDisableDPIScale": true,
    "DFIntTaskSchedulerTargetFps": 0,
    "FFlagAdServiceEnabled": false,
    "FFlagDebugDisableTelemetryEphemeralCounter": true,
    "FFlagDebugDisableTelemetryEphemeralStat": true,
    "FFlagDebugDisableTelemetryEventIngest": true,
    "FFlagDebugDisableTelemetryPoint": true,
    "FFlagDebugDisableTelemetryV2Counter": true,
    "FFlagDebugDisableTelemetryV2Event": true,
    "FFlagDebugDisableTelemetryV2Stat": true,
    "FFlagFixGraphicsQuality": true,
    "FFlagFutureIsBrightPhase3Vulkan": true,
    "FFlagGameBasicSettingsFramerateCap5": true,
    "FFlagHighlightOutlinesOnMobile": true,
    "FFlagHighlightsIntegratedWithGFX": false,
    "FFlagTextureDeduplicationByHash4": false,
    "FFlagUserHandleChatHotKeyWithContextActionService": true
}
"
2024-10-11T09:40:52.586Z,0.586570,3096b340,6 [FLog::AndroidGLView] nativePostClientSettingsLoadedInitialization3
2024-10-11T09:40:52.586Z,0.586654,3096b340,6 [FLog::ClientRunInfo] RobloxGitHash: 8d61301dd0968a21481f7fcd30d2ba323fbd0ded
2024-10-11T09:40:52.586Z,0.586665,3096b340,6 [FLog::ClientRunInfo] The base url is https://www.roblox.com/
2024-10-11T09:40:52.586Z,0.586682,3096b340,6 [FLog::ClientRunInfo] The channel is production
2024-10-11T09:40:52.592Z,0.592047,13a006c0,6 [FLog::SingleSurfaceApp] initializeWithAppStarter
2024-10-11T09:40:52.592Z,0.592070,13a006c0,6 [FLog::SingleSurfaceApp] initializeSingleton
2024-10-11T09:40:52.592Z,0.592167,13a006c0,6 [FLog::Output] setAssetFolder /home/tango/.var/app/org.vinegarhq.Sober/data/sober/assets/content/
2024-10-11T09:40:52.592Z,0.592292,13a006c0,6 [FLog::Output] setExtraAssetFolder /home/tango/.var/app/org.vinegarhq.Sober/data/sober/assets/ExtraContent
2024-10-11T09:40:52.592Z,0.592418,13a006c0,6 [FLog::Output] Evaluating deferred inferred crashes
2024-10-11T09:40:52.592Z,0.592544,13a006c0,6 [FLog::SingleSurfaceApp] registerForForceOTAUpdateAvailableConnection stage = 0
2024-10-11T09:40:52.592Z,0.592772,13a006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Load configs for user key: app:7165698806544101605
2024-10-11T09:40:52.593Z,0.593342,13a006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:Native)
2024-10-11T09:40:52.593Z,0.593358,13a006c0,6 [FLog::SingleSurfaceApp] instantiate controllers
2024-10-11T09:40:52.593Z,0.593364,13a006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::SurfaceController, count: 1
2024-10-11T09:40:52.593Z,0.593507,13a006c0,6 [FLog::SingleSurfaceApp] initializeLuaAppWithLoggedInUser: (stage:Native).
2024-10-11T09:40:52.593Z,0.593520,13a006c0,6 [FLog::SingleSurfaceApp] applyLocale
2024-10-11T09:40:52.594Z,0.594009,13a006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Retrieving patch
2024-10-11T09:40:52.594Z,0.594025,13a006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=5345954812, assetVersion=9692, maxAppVersion=642, localAssetURI=rbxasset://models/DataModelPatch/DataModelPatch.rbxm
2024-10-11T09:40:52.594Z,0.594038,13a006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : numAttempts=10
2024-10-11T09:40:52.594Z,0.594087,13a006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : contentId=rbxasset://models/DataModelPatch/DataModelPatch.rbxm
2024-10-11T09:40:52.594Z,0.594110,13a006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : get patch from content provider for Model
2024-10-11T09:40:52.594Z,0.594170,13a006c0,6 [FLog::DataModelPatchConfigurer] deserializeAndVerifyPatch with blake3
2024-10-11T09:40:52.886Z,0.886022,13a006c0,6 [FLog::Output] Hello? Is this thing on?
2024-10-11T09:40:52.886Z,0.886055,13a006c0,6 [FLog::Output] Hello world, nothing to see here...
2024-10-11T09:40:52.890Z,0.890265,13a006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:InitializedLuaApp)
2024-10-11T09:40:52.890Z,0.890614,131ff6c0,6 [FLog::Output] Info: DataModel Loading rbxasset://places/Mobile.rbxl
2024-10-11T09:40:52.901Z,0.901649,131ff6c0,6 [FLog::DataModelPatchConfigurer] OTAPollingEnabled set to: false
2024-10-11T09:40:52.910Z,0.910649,131ff6c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config
2024-10-11T09:40:53.035Z,1.035724,131ff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Load configs for user key: user:376674593
2024-10-11T09:40:53.035Z,1.035941,131ff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Retrieving patch
2024-10-11T09:40:53.035Z,1.035959,131ff6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=16639814581, assetVersion=933, maxAppVersion=642, localAssetURI=
2024-10-11T09:40:53.125Z,1.125078,11c006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-11T09:40:53.125Z,1.125123,11c006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config not deployed
2024-10-11T09:40:53.247Z,1.247599,131ff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA config
2024-10-11T09:40:53.278Z,1.278241,127ff6c0,6 [FLog::Warning] Warning: Unable to fetch completed survey ids from app storage  
2024-10-11T09:40:53.389Z,1.389207,13a006c0,6 [FLog::SingleSurfaceApp] startLuaApp: (stage:InitializedLuaApp).
2024-10-11T09:40:53.389Z,1.389260,13a006c0,6 [FLog::SingleSurfaceApp] returnToLuaApp: (stage:InitializedLuaApp).
2024-10-11T09:40:53.389Z,1.389269,13a006c0,6 [FLog::SingleSurfaceApp] returnToLuaApp: ... disable videoRecorder.
2024-10-11T09:40:53.389Z,1.389285,13a006c0,6 [FLog::SingleSurfaceApp] returnToLuaAppInternal: ... App has been initialized, returning from game.
2024-10-11T09:40:53.389Z,1.389298,13a006c0,6 [FLog::SurfaceController] [_:1]::replaceDataModel: (stage:0, window = 0x10) [tid:0x436ba440320]
2024-10-11T09:40:53.389Z,1.389456,13a006c0,6 [FLog::Graphics] Vulkan: Using extension: VK_KHR_surface
2024-10-11T09:40:53.389Z,1.389473,13a006c0,6 [FLog::Graphics] Vulkan: Using extension: VK_KHR_android_surface
2024-10-11T09:40:53.390Z,1.390301,11c006c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-11T09:40:53.390Z,1.390333,11c006c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA config not deployed
2024-10-11T09:40:53.396Z,1.396755,13bff6c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config
2024-10-11T09:40:53.444Z,1.444931,13a006c0,6 [FLog::Graphics] Vulkan Android Device: 
2024-10-11T09:40:53.445Z,1.445045,13a006c0,6 [FLog::Graphics] VULKAN MT shader loading is enabled
2024-10-11T09:40:53.445Z,1.445073,13a006c0,6 [FLog::Graphics] VULKAN heapIndex = 0, heapFlags = 1 (device), heapSize = 0
2024-10-11T09:40:53.445Z,1.445081,13a006c0,6 [FLog::Graphics] VULKAN heapIndex = 1, heapFlags = 0 (host), heapSize = 3939140608
2024-10-11T09:40:53.445Z,1.445086,13a006c0,6 [FLog::Graphics] VULKAN heapIndex = 2, heapFlags = 1 (device), heapSize = 257949696
2024-10-11T09:40:53.445Z,1.445093,13a006c0,6 [FLog::Graphics] VULKAN unifiedMemory = false, device memory = 8847884288, host memory = 12529075200, setting caps.videoMemory = 67108864
2024-10-11T09:40:53.445Z,1.445103,13a006c0,6 [FLog::Graphics] Vulkan Device: NVIDIA GeForce RTX 3070
2024-10-11T09:40:53.445Z,1.445109,13a006c0,6 [FLog::Graphics] Vulkan Device: Vendor 10de Device 2484
2024-10-11T09:40:53.445Z,1.445114,13a006c0,6 [FLog::Graphics] Vulkan Device: Driver 550.428.128 (-1986346880)
2024-10-11T09:40:53.445Z,1.445120,13a006c0,6 [FLog::Graphics] Vulkan Device: API 1.3.277
2024-10-11T09:40:53.445Z,1.445125,13a006c0,6 [FLog::Graphics] Caps: passFloatsLimit 1073741824
2024-10-11T09:40:53.445Z,1.445137,13a006c0,6 [channel] Caps: ThreadSafe 1 Framebuffer 1 FpFramebuffer 1 Shaders 1 Compute 1 Instancing 1 PerInstanceStream 1 ConstBuffers 1
2024-10-11T09:40:53.445Z,1.445143,13a006c0,6 [channel] Caps: Framebuffer: MRT 4 MSAA 8 Stencil 1
2024-10-11T09:40:53.445Z,1.445149,13a006c0,6 [channel] Caps: Framebuffer: Depth16 1 Depth24 1 DepthFloat 1 DepthClamp 1
2024-10-11T09:40:53.445Z,1.445154,13a006c0,6 [channel] Caps: Border Color 1
2024-10-11T09:40:53.445Z,1.445166,13a006c0,6 [channel] Caps: Texture: RGB10A2 1 RG11B10F 1 R16I 1
2024-10-11T09:40:53.445Z,1.445171,13a006c0,6 [channel] Caps: Texture: BC6H 1 ASTC HDR 0
2024-10-11T09:40:53.445Z,1.445175,13a006c0,6 [channel] Caps: Texture: DXT 1 PVR 0 ETC1 0 ETC2 0 Half 1
2024-10-11T09:40:53.445Z,1.445179,13a006c0,6 [channel] Caps: Texture: 3D 1 Array 1 Depth 1 MSAA 1 MSAAFP16 8
2024-10-11T09:40:53.445Z,1.445184,13a006c0,6 [channel] Caps: Texture: NPOT 1 PartialMips 1 CubeMipGen 1 CubeFramebuffer 1
2024-10-11T09:40:53.445Z,1.445188,13a006c0,6 [channel] Caps: Texture: Size 32768 Units 32 VertexUnits 32
2024-10-11T09:40:53.445Z,1.445193,13a006c0,6 [channel] Caps: ConstantBufferSize 16384
2024-10-11T09:40:53.445Z,1.445201,13a006c0,6 [channel] Caps: isAppleGPU 0
2024-10-11T09:40:53.445Z,1.445205,13a006c0,6 [channel] Caps: 32bIdx 1 Memoryless 0
2024-10-11T09:40:53.445Z,1.445210,13a006c0,6 [channel] Caps: ColorBGR 0 RTFlip 0 MinusOneToOneDepth 0
2024-10-11T09:40:53.449Z,1.449760,13a006c0,6 [FLog::Graphics] Vulkan: Loaded pipeline cache (6579603 bytes, hash 405c6fe3)
2024-10-11T09:40:53.464Z,1.464907,13a006c0,6 [FLog::Graphics] Vulkan: creating framebuffer 800x600
2024-10-11T09:40:53.520Z,1.520604,13a006c0,6 [FLog::Graphics] Vulkan: swapchain images 3 present mode 0 format 44
2024-10-11T09:40:53.520Z,1.520997,13a006c0,6 [FLog::Graphics] Video memory size: 67108864
2024-10-11T09:40:53.529Z,1.529238,13a006c0,6 [FLog::Graphics] Loaded 886 shaders from pack vulkan_mobile variant defaultLightingRefactor (8087342 bytes)
2024-10-11T09:40:53.529Z,1.529283,13a006c0,6 [FLog::Graphics] Compiled 672 shaders in 8 ms
2024-10-11T09:40:53.539Z,1.539302,13a006c0,6 [FLog::SurfaceController] SurfaceController::disableVR
2024-10-11T09:40:53.539Z,1.539372,13a006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::initialize view(0x436c7b85780)
2024-10-11T09:40:53.539Z,1.539420,13a006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::start dataModel(0x436c3a7ff60)
2024-10-11T09:40:53.539Z,1.539442,13a006c0,6 [FLog::SurfaceController] SurfaceController::RenderJob[_:1]::RenderJob
2024-10-11T09:40:53.539Z,1.539455,13a006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::run dataModel(0x436c3a7ff60)
2024-10-11T09:40:53.539Z,1.539489,13a006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:LuaApp)
2024-10-11T09:40:53.539Z,1.539598,13a006c0,6 [FLog::SingleSurfaceApp] userDidLogin
2024-10-11T09:40:53.539Z,1.539613,13a006c0,6 [FLog::SingleSurfaceApp] applyLocale
2024-10-11T09:40:53.549Z,1.549679,127ff6c0,6 [FLog::SurfaceController] SurfaceController::RenderJob::stepDataModelJob: No DM yet. Continue...
2024-10-11T09:40:53.549Z,1.549756,13a006c0,6 [FLog::SurfaceController] SurfaceController::RenderJob::scheduleRender: No data model. Bind workspace now...
2024-10-11T09:40:53.603Z,1.603108,13a006c0,6 [FLog::Graphics] Vulkan: resizing window framebuffer to 800x600
2024-10-11T09:40:53.605Z,1.605625,13a006c0,6 [FLog::Graphics] Vulkan: swapchain images 3 present mode 0 format 44
2024-10-11T09:40:53.605Z,1.605793,13a006c0,6 [FLog::Graphics] LayeredClothingMode updated: LC=1 HSR=1
2024-10-11T09:40:53.605Z,1.605824,13a006c0,6 [FLog::Graphics] Future is bright shadows
2024-10-11T09:40:53.609Z,1.609311,11c006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-11T09:40:53.609Z,1.609358,11c006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config not deployed
2024-10-11T09:40:53.610Z,1.610308,13a006c0,6 [FLog::Graphics] SmoothCluster::initSolidTextures()
2024-10-11T09:40:53.610Z,1.610375,13a006c0,6 [FLog::Graphics] Terrain TextureAtlas 2048x2048, tileCount: 6x6, tileSize: 256x256, border: 32, mip: 4
2024-10-11T09:40:53.612Z,1.612989,13a006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 800x600
2024-10-11T09:40:53.629Z,1.629496,127ff6c0,6 [FLog::Error] Asset (Image) "rbxthumb://type=AvatarHeadShot&id=&w=48&h=48&filters=circular" load failed in TextureManager::PreloadTexture: Request failed
2024-10-11T09:40:53.629Z,1.629543,131ff6c0,6 [FLog::Warning] Warning: HTTP error url:`https://apis.roblox.com/attribution/v1/events/post-authentication`
2024-10-11T09:40:53.629Z,1.629623,131ff6c0,6 [FLog::Warning] Warning: HTTP error code:`nil`
2024-10-11T09:40:53.629Z,1.629645,131ff6c0,6 [FLog::Warning] Warning: HTTP error body:`nil`
2024-10-11T09:40:53.970Z,1.970076,13bff6c0,6 [FLog::Error] Asset (Image) "rbxthumb://type=AvatarHeadShot&id=-1&w=48&h=48&filters=circular" load failed in TextureManager::PreloadTexture: Request failed
2024-10-11T09:41:04.503Z,12.503877,13a006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 800x600
2024-10-11T09:41:07.003Z,15.003579,13a006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 800x600
2024-10-11T09:41:09.503Z,17.503748,13a006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 800x600```

the logs showed nothing when sober crashed.

### Roblox Experience link

_No response_

**Comment by MatTrof** [comment] 2024-10-11 09:48
oops i may or may not have incorrectly closed the tag

**Comment by apprehensions** [comment] 2024-10-11 09:49
> I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

You haven't. Duplicate of #297

**Comment by MatTrof** [comment] 2024-10-11 09:49
> > I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.
> 
> You haven't. Duplicate of #297

oops

**Closed by apprehensions** 2024-10-11 09:49 UTC
Labels: bug

**Comment by kirbix12** [comment] 2024-10-11 09:52
Please update Sober. New update has been published that fixes this.

**Comment by MatTrof** [comment] 2024-10-11 09:57
> Please update Sober. New update has been published that fixes this.

![image](https://github.com/user-attachments/assets/72d9fc4b-785e-4d85-b7e8-590ccac72739)

im a linux rookie, what the hell is this

**Comment by kirbix12** [comment] 2024-10-11 10:15
I guess telling you to update was a bad idea ☠️ /s

Run `flatpak update` on your terminal.

**Comment by SPLDevelop** [comment] 2024-10-12 17:15
try putting in your terminal `flatpak update org.vinegarhq.Sober`, this should not just update Sober but everything is necessary/correlated to Sober, by only putting `flatpak update` you're going to update EVERYTHING that is in flathub/was installed by flatpak, and if you has installed a lot of apps you'll have to wait a little bit to much.

**Comment by SPLDevelop** [comment] 2024-10-12 17:18
by the way, the problem you got here is 'cuz org.gnome isn't updated, this is fixed by putting `flatpak update org.vinegarhq.Sober` too. Other possible problem is that org.gnome isn't even installed.
