### ISSUE TITLE
Mouse cursor jumps positions after holding right click to move the camera

### ISSUE THREAD

**Issue by pinner3402** [vinegarhq/sober#61] opened 2024-08-08 00:06 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Here is my log.](https://github.com/user-attachments/files/16536099/2.636.0.626_20240808T002240Z_Player_9719f_last.log)
This only happens in this particular game _as far as I know_, Check the Experience Link.

https://github.com/user-attachments/assets/a981fd74-eb2c-4721-9232-a93c9d2a8e4d

### Roblox Experience link

https://www.roblox.com/games/6209557373

**Comment by km9l** [comment] 2024-08-08 02:16
this is the first time im seeing this bug, but i can reproduce it in that game

**Comment by tunis4** [comment] 2024-08-08 16:50
duplicate of #51

**Closed** 2024-08-08 16:51 UTC
Labels: bug
