### ISSUE TITLE
phantom forces test place out of memory error

### ISSUE THREAD

**Issue by Xgameisdabest** [vinegarhq/sober#365] opened 2024-10-28 15:58 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i just tried to launch phatom forces test place but it got this error:
RBXCRASH: OutOfMemory (swOcc_alloc failed on 32768 bytes 4 alignment)

the main game works fine but this does not seem well

### Roblox Experience link

https://www.roblox.com/games/299659045/test-place

**Comment by Xgameisdabest** [comment] 2024-10-28 16:26
i have 16gbs of ram btw

**Comment by tunis4** [comment] 2024-10-28 19:46
duplicate of #351, use the workaround there

**Closed by tunis4** 2024-10-28 19:46 UTC
Labels: bug
