### ISSUE TITLE
Crashing right after joing experience

### ISSUE THREAD

**Issue by Supply12** [vinegarhq/sober#313] opened 2024-10-12 10:41 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sober crashing right after joining experience, installed with flatpak, autoinstall apk

`2024-10-12T10:37:52.975Z,2.975109,e0efe6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : t13:37:53 [50/360]
639814581, assetVersion=933, maxAppVersion=642, localAssetURI=                                                                        
2024-10-12T10:37:53.177Z,3.177418,e0fff6c0,6 [FLog::Warning] Warning: Unable to fetch completed survey ids from app storage           
2024-10-12T10:37:53.177Z,3.177628,e0fff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA config                       
nativeAppBridgeV2StartApp:                                                                                                            
nativeAppBridgeV2StartApp: Created ANativeWindow 0x10 (ID:1)                                                                          
2024-10-12T10:37:53.284Z,3.284269,dde006c0,6 [FLog::SingleSurfaceApp] startLuaApp: (stage:InitializedLuaApp).                         
2024-10-12T10:37:53.284Z,3.284296,dde006c0,6 [FLog::SingleSurfaceApp] returnToLuaApp: (stage:InitializedLuaApp).                      
2024-10-12T10:37:53.284Z,3.284316,dde006c0,6 [FLog::SingleSurfaceApp] returnToLuaApp: ... disable videoRecorder.                      
2024-10-12T10:37:53.284Z,3.284321,dde006c0,6 [FLog::SingleSurfaceApp] returnToLuaAppInternal: ... App has been initialized, returning 
from game.                                                                                                                            
2024-10-12T10:37:53.284Z,3.284329,dde006c0,6 [FLog::SurfaceController] [_:1]::replaceDataModel: (stage:0, window = 0x10) [tid:0x50fabc
40320]                                                                                                                                
2024-10-12T10:37:53.284Z,3.284491,dde006c0,6 [FLog::Graphics] Vulkan: Using extension: VK_KHR_surface                                 
2024-10-12T10:37:53.284Z,3.284500,dde006c0,6 [FLog::Graphics] Vulkan: Using extension: VK_KHR_android_surface                         
2024-10-12T10:37:53.289Z,3.289577,e0efe6c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config                     
2024-10-12T10:37:53.393Z,3.393234,dde006c0,6 [FLog::Graphics] Vulkan Android Device:                                                  
2024-10-12T10:37:53.393Z,3.393311,dde006c0,6 [FLog::Graphics] VULKAN MT shader loading is enabled                                     
2024-10-12T10:37:53.393Z,3.393331,dde006c0,6 [FLog::Graphics] VULKAN heapIndex = 0, heapFlags = 1 (device), heapSize = 2147483648     
2024-10-12T10:37:53.393Z,3.393339,dde006c0,6 [FLog::Graphics] VULKAN heapIndex = 1, heapFlags = 0 (host), heapSize = 3926751232       
2024-10-12T10:37:53.393Z,3.393345,dde006c0,6 [FLog::Graphics] VULKAN unifiedMemory = false, device memory = 2147483648, host memory = 
12516685824, setting caps.videoMemory = 67108864                                                                                      
2024-10-12T10:37:53.393Z,3.393352,dde006c0,6 [FLog::Graphics] Vulkan Device: NVIDIA GeForce GT 710                                    
2024-10-12T10:37:53.393Z,3.393357,dde006c0,6 [FLog::Graphics] Vulkan Device: Vendor 10de Device 128b                                  
2024-10-12T10:37:53.393Z,3.393361,dde006c0,6 [FLog::Graphics] Vulkan Device: Driver 471.0.128 (1975517312)                            
2024-10-12T10:37:53.393Z,3.393365,dde006c0,6 [FLog::Graphics] Vulkan Device: API 1.2.175                                              
2024-10-12T10:37:53.393Z,3.393369,dde006c0,6 [FLog::Graphics] Caps: passFloatsLimit 1073741824                                        
2024-10-12T10:37:53.393Z,3.393373,dde006c0,6 [channel] Caps: ThreadSafe 1 Framebuffer 1 FpFramebuffer 1 Shaders 1 Compute 1 Instancing
 1 PerInstanceStream 1 ConstBuffers 1                                                                                                 
2024-10-12T10:37:53.393Z,3.393378,dde006c0,6 [channel] Caps: Framebuffer: MRT 4 MSAA 8 Stencil 1                                      
2024-10-12T10:37:53.393Z,3.393382,dde006c0,6 [channel] Caps: Framebuffer: Depth16 1 Depth24 1 DepthFloat 1 DepthClamp 1               
2024-10-12T10:37:53.393Z,3.393386,dde006c0,6 [channel] Caps: Border Color 1                                                           
2024-10-12T10:37:53.393Z,3.393392,dde006c0,6 [channel] Caps: Texture: RGB10A2 1 RG11B10F 1 R16I 1                                     
2024-10-12T10:37:53.393Z,3.393396,dde006c0,6 [channel] Caps: Texture: BC6H 1 ASTC HDR 0                                               
2024-10-12T10:37:53.393Z,3.393399,dde006c0,6 [channel] Caps: Texture: DXT 1 PVR 0 ETC1 0 ETC2 0 Half 1                                
2024-10-12T10:37:53.393Z,3.393403,dde006c0,6 [channel] Caps: Texture: 3D 1 Array 1 Depth 1 MSAA 1 MSAAFP16 8                          
2024-10-12T10:37:53.393Z,3.393407,dde006c0,6 [channel] Caps: Texture: NPOT 1 PartialMips 1 CubeMipGen 1 CubeFramebuffer 1             
2024-10-12T10:37:53.393Z,3.393410,dde006c0,6 [channel] Caps: Texture: Size 16384 Units 32 VertexUnits 32                              
2024-10-12T10:37:53.393Z,3.393414,dde006c0,6 [channel] Caps: ConstantBufferSize 16384                                                 
2024-10-12T10:37:53.393Z,3.393430,dde006c0,6 [channel] Caps: isAppleGPU 0                                                             
2024-10-12T10:37:53.393Z,3.393434,dde006c0,6 [channel] Caps: 32bIdx 1 Memoryless 0                                                    
2024-10-12T10:37:53.393Z,3.393438,dde006c0,6 [channel] Caps: ColorBGR 0 RTFlip 0 MinusOneToOneDepth 0                                 
2024-10-12T10:37:53.396Z,3.396672,dde006c0,6 [FLog::Graphics] Vulkan: Loaded pipeline cache (4378221 bytes, hash f71d23df)            
2024-10-12T10:37:53.400Z,3.400998,dde006c0,6 [FLog::Graphics] Vulkan: creating framebuffer 800x600                                    
2024-10-12T10:37:53.477Z,3.477864,dde006c0,6 [FLog::Graphics] Vulkan: swapchain images 3 present mode 0 format 44                     
2024-10-12T10:37:53.478Z,3.478715,dde006c0,6 [FLog::Graphics] Video memory size: 67108864                                             
2024-10-12T10:37:53.483Z,3.483553,dde006c0,6 [FLog::Graphics] Loaded 886 shaders from pack vulkan_mobile variant defaultLightingRefact
or (8118158 bytes)                                                                                                                    
2024-10-12T10:37:53.483Z,3.483573,dde006c0,6 [FLog::Graphics] Compiled 672 shaders in 4 ms                                            
2024-10-12T10:37:53.495Z,3.495519,dde006c0,6 [FLog::SurfaceController] SurfaceController::disableVR     
2024-10-12T10:37:53.495Z,3.495561,dde006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::initialize view(0x50fb9804d00)
2024-10-12T10:37:53.495Z,3.495607,dde006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::start dataModel(0x50face825b0)
2024-10-12T10:37:53.495Z,3.495626,dde006c0,6 [FLog::SurfaceController] SurfaceController::RenderJob[_:1]::RenderJob
2024-10-12T10:37:53.495Z,3.495637,dde006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::run dataModel(0x50face825b0)
2024-10-12T10:37:53.495Z,3.495657,dde006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:LuaApp)
2024-10-12T10:37:53.495Z,3.495748,dde006c0,6 [FLog::SingleSurfaceApp] userDidLogin
2024-10-12T10:37:53.495Z,3.495759,dde006c0,6 [FLog::SingleSurfaceApp] applyLocale
2024-10-12T10:37:53.509Z,3.509368,e0fff6c0,6 [FLog::SurfaceController] SurfaceController::RenderJob::stepDataModelJob: No DM yet. Continue...
2024-10-12T10:37:53.509Z,3.509407,dde006c0,6 [FLog::SurfaceController] SurfaceController::RenderJob::scheduleRender: No data model. Bind workspace now...
2024-10-12T10:37:53.524Z,3.524615,dde006c0,6 [FLog::Graphics] Vulkan: resizing window framebuffer to 800x600
2024-10-12T10:37:53.575Z,3.575149,dde006c0,6 [FLog::Graphics] Vulkan: swapchain images 3 present mode 0 format 44
2024-10-12T10:37:53.575Z,3.575285,dde006c0,6 [FLog::Graphics] LayeredClothingMode updated: LC=1 HSR=1
2024-10-12T10:37:53.575Z,3.575302,dde006c0,6 [FLog::Graphics] Future is bright shadows
2024-10-12T10:37:53.580Z,3.580380,dde006c0,6 [FLog::Graphics] SmoothCluster::initSolidTextures()
2024-10-12T10:37:53.580Z,3.580424,dde006c0,6 [FLog::Graphics] Terrain TextureAtlas 2048x2048, tileCount: 6x6, tileSize: 256x256, border: 32, mip: 4
2024-10-12T10:37:53.581Z,3.581749,dde006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 800x600
2024-10-12T10:37:53.591Z,3.591201,d3a006c0,12 [DFLog::HttpTraceError] HttpResponse(#13 0x50fbb7d8a20) time:300.3ms (net:0.0ms callback:0.0ms timeInRetryQueue:0.0ms) error:9 message:HttpError: Aborted url:{ "https://apis.roblox.com/product-experimentation-platform/v1/projects/1/values" } ip: external:0 numberOfTimesRetried:0
nativeAppBridgeAppStart: StartupController finished starting: stage = 2, BTID = 0, upgradeStatus = 3.
2024-10-12T10:37:53.635Z,3.635250,e0fff6c0,6 [FLog::Error] Asset (Image) "rbxthumb://type=AvatarHeadShot&id=&w=48&h=48&filters=circular" load failed in TextureManager::PreloadTexture: Request failed
2024-10-12T10:37:53.645Z,3.645794,d3a006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-12T10:37:53.645Z,3.645828,d3a006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config not deployed
2024-10-12T10:37:53.926Z,3.926524,d3a006c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-12T10:37:53.926Z,3.926581,d3a006c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA config not deployed
2024-10-12T10:37:54.050Z,4.050176,e0efe6c0,6 [FLog::Warning] Warning: HTTP error url:`https://apis.roblox.com/attribution/v1/events/post-authentication`
2024-10-12T10:37:54.050Z,4.050232,e0efe6c0,6 [FLog::Warning] Warning: HTTP error code:`nil`
2024-10-12T10:37:54.050Z,4.050240,e0efe6c0,6 [FLog::Warning] Warning: HTTP error body:`nil`
2024-10-12T10:37:54.306Z,4.306758,d3a006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-12T10:37:54.306Z,4.306802,d3a006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config not deployed
2024-10-12T10:37:54.628Z,4.628896,e0fff6c0,6 [FLog::Error] Asset (Image) "rbxthumb://type=AvatarHeadShot&id=-1&w=48&h=48&filters=circular" load failed in TextureManager::PreloadTexture: Request failed
2024-10-12T10:37:59.376Z,9.376775,dde006c0,6 [FLog::Graphics] Vulkan: resizing window framebuffer to 1920x1016
nativeAppBridgeV2UpdateSurfaceApp:
nativeAppBridgeV2UpdateSurfaceApp: Same native window 0x10. No need to do anything!
2024-10-12T10:37:59.402Z,9.402485,dde006c0,6 [FLog::Graphics] Vulkan: swapchain images 3 present mode 0 format 44
2024-10-12T10:37:59.403Z,9.403834,dde006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 1920x1016
2024-10-12T10:37:59.429Z,9.429807,dde006c0,6 [FLog::SingleSurfaceApp] updateSurfaceLuaApp: (stage:LuaApp)
2024-10-12T10:37:59.429Z,9.429837,dde006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::update: (window = 0x10) (view = 0x50fb9804d00)
2024-10-12T10:38:00.663Z,10.663412,dde006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 1920x1016
2024-10-12T10:38:00.850Z,10.850172,dde006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 1920x1016
2024-10-12T10:38:04.353Z,14.353781,dde006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 1920x1016
nativeAppBridgeV2StartGameWithParam:
nativeAppBridgeV2StartGameWithParam: Same native window 0x10. No need to do anything`

**Comment by tunis4** [comment] 2024-10-12 10:57
update sober

duplicate of #297

**Closed by tunis4** 2024-10-12 10:57 UTC
Labels: bug
