### ISSUE TITLE
Crashing after joining a map. (arch-linux)

### ISSUE THREAD

**Issue by UnitieG** [vinegarhq/sober#312] opened 2024-10-12 08:09 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-10-12T08:08:30.587Z,1.587748,29d23340,6 [FLog::AndroidGLView] nativeInitClientSettings
2024-10-12T08:08:30.597Z,1.597439,29d23340,6 [FLog::Output] LoadClientSettingsFromLocal: "{
    "DFFlagDisableDPIScale": true,
    "DFIntTaskSchedulerTargetFps": 0,
    "FFlagAdServiceEnabled": false,
    "FFlagDebugDisableTelemetryEphemeralCounter": true,
    "FFlagDebugDisableTelemetryEphemeralStat": true,
    "FFlagDebugDisableTelemetryEventIngest": true,
    "FFlagDebugDisableTelemetryPoint": true,
    "FFlagDebugDisableTelemetryV2Counter": true,
    "FFlagDebugDisableTelemetryV2Event": true,
    "FFlagDebugDisableTelemetryV2Stat": true,
    "FFlagFixGraphicsQuality": true,
    "FFlagFutureIsBrightPhase3Vulkan": true,
    "FFlagGameBasicSettingsFramerateCap5": true,
    "FFlagHighlightOutlinesOnMobile": true,
    "FFlagHighlightsIntegratedWithGFX": false,
    "FFlagTextureDeduplicationByHash4": false,
    "FFlagUserHandleChatHotKeyWithContextActionService": true
}
"
2024-10-12T08:08:30.598Z,1.598411,29d23340,6 [FLog::AndroidGLView] nativePostClientSettingsLoadedInitialization3
2024-10-12T08:08:30.598Z,1.598474,29d23340,6 [FLog::ClientRunInfo] RobloxGitHash: 8d61301dd0968a21481f7fcd30d2ba323fbd0ded
2024-10-12T08:08:30.598Z,1.598482,29d23340,6 [FLog::ClientRunInfo] The base url is https://www.roblox.com/
2024-10-12T08:08:30.598Z,1.598487,29d23340,6 [FLog::ClientRunInfo] The channel is production
2024-10-12T08:08:30.604Z,1.604061,c2006c0,6 [FLog::SingleSurfaceApp] initializeWithAppStarter
2024-10-12T08:08:30.604Z,1.604096,c2006c0,6 [FLog::SingleSurfaceApp] initializeSingleton
2024-10-12T08:08:30.604Z,1.604184,c2006c0,6 [FLog::Output] setAssetFolder /home/furrygang/.var/app/org.vinegarhq.Sober/data/sober/assets/content/
2024-10-12T08:08:30.604Z,1.604304,c2006c0,6 [FLog::Output] setExtraAssetFolder /home/furrygang/.var/app/org.vinegarhq.Sober/data/sober/assets/ExtraContent
2024-10-12T08:08:30.604Z,1.604426,c2006c0,6 [FLog::Output] Evaluating deferred inferred crashes
2024-10-12T08:08:30.604Z,1.604552,c2006c0,6 [FLog::SingleSurfaceApp] registerForForceOTAUpdateAvailableConnection stage = 0
2024-10-12T08:08:30.604Z,1.604777,c2006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Load configs for user key: app:8110787811448022080
2024-10-12T08:08:30.605Z,1.605415,c2006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:Native)
2024-10-12T08:08:30.605Z,1.605431,c2006c0,6 [FLog::SingleSurfaceApp] instantiate controllers
2024-10-12T08:08:30.605Z,1.605446,c2006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::SurfaceController, count: 1
2024-10-12T08:08:30.605Z,1.605626,c2006c0,6 [FLog::SingleSurfaceApp] initializeLuaAppWithLoggedInUser: (stage:Native).
2024-10-12T08:08:30.605Z,1.605641,c2006c0,6 [FLog::SingleSurfaceApp] applyLocale
2024-10-12T08:08:30.606Z,1.606161,c2006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Retrieving patch
2024-10-12T08:08:30.606Z,1.606177,c2006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=5345954812, assetVersion=9692, maxAppVersion=642, localAssetURI=rbxasset://models/DataModelPatch/DataModelPatch.rbxm
2024-10-12T08:08:30.606Z,1.606194,c2006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : numAttempts=10
2024-10-12T08:08:30.606Z,1.606271,c2006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : contentId=rbxasset://models/DataModelPatch/DataModelPatch.rbxm
2024-10-12T08:08:30.606Z,1.606283,c2006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : get patch from content provider for Model
2024-10-12T08:08:30.606Z,1.606334,c2006c0,6 [FLog::DataModelPatchConfigurer] deserializeAndVerifyPatch with blake3
2024-10-12T08:08:30.917Z,1.917441,c2006c0,6 [FLog::Output] Hello? Is this thing on?
2024-10-12T08:08:30.917Z,1.917467,c2006c0,6 [FLog::Output] Hello world, nothing to see here...
2024-10-12T08:08:30.921Z,1.921900,c2006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:InitializedLuaApp)
2024-10-12T08:08:30.922Z,1.922210,141ff6c0,6 [FLog::Output] Info: DataModel Loading rbxasset://places/Mobile.rbxl
2024-10-12T08:08:30.932Z,1.932069,141ff6c0,6 [FLog::DataModelPatchConfigurer] OTAPollingEnabled set to: false
2024-10-12T08:08:30.941Z,1.941060,141ff6c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config
2024-10-12T08:08:31.073Z,2.073780,141ff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Load configs for user key: user:2950337461
2024-10-12T08:08:31.073Z,2.073955,141ff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Retrieving patch
2024-10-12T08:08:31.073Z,2.073969,141ff6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=16639814581, assetVersion=933, maxAppVersion=642, localAssetURI=
2024-10-12T08:08:31.240Z,2.240001,a4006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-12T08:08:31.240Z,2.240042,a4006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config not deployed
2024-10-12T08:08:31.320Z,2.320328,141ff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA config
2024-10-12T08:08:31.329Z,2.329680,c3ff6c0,6 [FLog::Warning] Warning: Unable to fetch completed survey ids from app storage  
2024-10-12T08:08:31.411Z,2.411204,c2006c0,6 [FLog::SingleSurfaceApp] startLuaApp: (stage:InitializedLuaApp).
2024-10-12T08:08:31.411Z,2.411230,c2006c0,6 [FLog::SingleSurfaceApp] returnToLuaApp: (stage:InitializedLuaApp).
2024-10-12T08:08:31.411Z,2.411245,c2006c0,6 [FLog::SingleSurfaceApp] returnToLuaApp: ... disable videoRecorder.
2024-10-12T08:08:31.411Z,2.411251,c2006c0,6 [FLog::SingleSurfaceApp] returnToLuaAppInternal: ... App has been initialized, returning from game.
2024-10-12T08:08:31.411Z,2.411258,c2006c0,6 [FLog::SurfaceController] [_:1]::replaceDataModel: (stage:0, window = 0x10) [tid:0x2992d440220]
2024-10-12T08:08:31.411Z,2.411420,c2006c0,6 [FLog::Graphics] Vulkan: Using extension: VK_KHR_surface
2024-10-12T08:08:31.411Z,2.411439,c2006c0,6 [FLog::Graphics] Vulkan: Using extension: VK_KHR_android_surface
2024-10-12T08:08:31.418Z,2.418679,141ff6c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config
2024-10-12T08:08:31.423Z,2.423541,c2006c0,6 [FLog::Graphics] Vulkan: Device llvmpipe (LLVM 17.0.6, 256 bits) is emulated, skipping
2024-10-12T08:08:31.428Z,2.428841,c2006c0,6 [FLog::Graphics] Vulkan Android Device: 
2024-10-12T08:08:31.428Z,2.428913,c2006c0,6 [FLog::Graphics] VULKAN MT shader loading is enabled
2024-10-12T08:08:31.428Z,2.428934,c2006c0,6 [FLog::Graphics] VULKAN heapIndex = 0, heapFlags = 1 (device), heapSize = 1610612736
2024-10-12T08:08:31.428Z,2.428940,c2006c0,6 [FLog::Graphics] VULKAN unifiedMemory = true, device memory = 1610612736, host memory = 0, setting caps.videoMemory = 67108864
2024-10-12T08:08:31.428Z,2.428978,c2006c0,6 [FLog::Graphics] Vulkan Device: Intel(R) HD Graphics 4600 (HSW GT2)
2024-10-12T08:08:31.428Z,2.428985,c2006c0,6 [FLog::Graphics] Vulkan Device: Vendor 8086 Device 0412
2024-10-12T08:08:31.428Z,2.428989,c2006c0,6 [FLog::Graphics] Vulkan Device: Driver 24.2.3 (100671491)
2024-10-12T08:08:31.429Z,2.429011,c2006c0,6 [FLog::Graphics] Vulkan Device: API 1.2.289
2024-10-12T08:08:31.429Z,2.429015,c2006c0,6 [FLog::Graphics] Caps: passFloatsLimit 1073741824
2024-10-12T08:08:31.429Z,2.429019,c2006c0,6 [channel] Caps: ThreadSafe 1 Framebuffer 1 FpFramebuffer 1 Shaders 1 Compute 1 Instancing 1 PerInstanceStream 1 ConstBuffers 1
2024-10-12T08:08:31.429Z,2.429024,c2006c0,6 [channel] Caps: Framebuffer: MRT 4 MSAA 8 Stencil 1
2024-10-12T08:08:31.429Z,2.429028,c2006c0,6 [channel] Caps: Framebuffer: Depth16 1 Depth24 1 DepthFloat 1 DepthClamp 1
2024-10-12T08:08:31.429Z,2.429032,c2006c0,6 [channel] Caps: Border Color 1
2024-10-12T08:08:31.429Z,2.429041,c2006c0,6 [channel] Caps: Texture: RGB10A2 1 RG11B10F 1 R16I 1
2024-10-12T08:08:31.429Z,2.429045,c2006c0,6 [channel] Caps: Texture: BC6H 1 ASTC HDR 0
2024-10-12T08:08:31.429Z,2.429049,c2006c0,6 [channel] Caps: Texture: DXT 1 PVR 0 ETC1 0 ETC2 0 Half 1
2024-10-12T08:08:31.429Z,2.429055,c2006c0,6 [channel] Caps: Texture: 3D 1 Array 1 Depth 1 MSAA 1 MSAAFP16 8
2024-10-12T08:08:31.429Z,2.429059,c2006c0,6 [channel] Caps: Texture: NPOT 1 PartialMips 1 CubeMipGen 1 CubeFramebuffer 1
2024-10-12T08:08:31.429Z,2.429071,c2006c0,6 [channel] Caps: Texture: Size 8192 Units 32 VertexUnits 32
2024-10-12T08:08:31.429Z,2.429075,c2006c0,6 [channel] Caps: ConstantBufferSize 16384
2024-10-12T08:08:31.429Z,2.429081,c2006c0,6 [channel] Caps: isAppleGPU 0
2024-10-12T08:08:31.429Z,2.429087,c2006c0,6 [channel] Caps: 32bIdx 1 Memoryless 0
2024-10-12T08:08:31.429Z,2.429091,c2006c0,6 [channel] Caps: ColorBGR 0 RTFlip 0 MinusOneToOneDepth 0
2024-10-12T08:08:31.429Z,2.429637,c2006c0,6 [FLog::Graphics] Vulkan: Loaded pipeline cache (729672 bytes, hash b60b54e4)
2024-10-12T08:08:31.431Z,2.431713,c2006c0,6 [FLog::Graphics] Vulkan: creating framebuffer 800x600
2024-10-12T08:08:31.433Z,2.433436,c2006c0,6 [FLog::Graphics] Vulkan: swapchain images 3 present mode 0 format 44
2024-10-12T08:08:31.433Z,2.433531,c2006c0,6 [FLog::Graphics] Video memory size: 67108864
2024-10-12T08:08:31.444Z,2.444063,c2006c0,6 [FLog::Graphics] Loaded 886 shaders from pack vulkan_mobile variant defaultLightingRefactor (8082686 bytes)
2024-10-12T08:08:31.444Z,2.444108,c2006c0,6 [FLog::Graphics] Compiled 672 shaders in 10 ms
2024-10-12T08:08:31.453Z,2.453723,c2006c0,6 [FLog::SurfaceController] SurfaceController::disableVR
2024-10-12T08:08:31.453Z,2.453854,c2006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::initialize view(0x2993b043000)
2024-10-12T08:08:31.453Z,2.453912,c2006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::start dataModel(0x2993a1af3b0)
2024-10-12T08:08:31.453Z,2.453940,c2006c0,6 [FLog::SurfaceController] SurfaceController::RenderJob[_:1]::RenderJob
2024-10-12T08:08:31.453Z,2.453952,c2006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::run dataModel(0x2993a1af3b0)
2024-10-12T08:08:31.461Z,2.461323,c2006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:LuaApp)
2024-10-12T08:08:31.461Z,2.461525,c2006c0,6 [FLog::SingleSurfaceApp] userDidLogin
2024-10-12T08:08:31.461Z,2.461543,c2006c0,6 [FLog::SingleSurfaceApp] applyLocale
2024-10-12T08:08:31.464Z,2.464600,c3ff6c0,6 [FLog::SurfaceController] SurfaceController::RenderJob::stepDataModelJob: No DM yet. Continue...
2024-10-12T08:08:31.464Z,2.464676,c2006c0,6 [FLog::SurfaceController] SurfaceController::RenderJob::scheduleRender: No data model. Bind workspace now...
2024-10-12T08:08:31.471Z,2.471128,c2006c0,6 [FLog::Graphics] Vulkan: resizing window framebuffer to 800x600
2024-10-12T08:08:31.497Z,2.497254,c2006c0,6 [FLog::Graphics] Vulkan: swapchain images 3 present mode 0 format 44
2024-10-12T08:08:31.498Z,2.498182,c2006c0,6 [FLog::Graphics] LayeredClothingMode updated: LC=1 HSR=1
2024-10-12T08:08:31.498Z,2.498216,c2006c0,6 [FLog::Graphics] Future is bright shadows
2024-10-12T08:08:31.508Z,2.508955,c2006c0,6 [FLog::Graphics] SmoothCluster::initSolidTextures()
2024-10-12T08:08:31.509Z,2.509064,c2006c0,6 [FLog::Graphics] Terrain TextureAtlas 2048x2048, tileCount: 6x6, tileSize: 256x256, border: 32, mip: 4
2024-10-12T08:08:31.514Z,2.514933,c2006c0,6 [FLog::Graphics] SceneManager: resizing main targets to 800x600
2024-10-12T08:08:31.557Z,2.557132,a4006c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-12T08:08:31.557Z,2.557178,a4006c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA config not deployed
2024-10-12T08:08:31.618Z,2.618392,141ff6c0,6 [FLog::Error] Asset (Image) "rbxthumb://type=AvatarHeadShot&id=&w=48&h=48&filters=circular" load failed in TextureManager::PreloadTexture: Request failed
2024-10-12T08:08:31.781Z,2.781789,a4006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
2024-10-12T08:08:31.781Z,2.781875,a4006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config not deployed
2024-10-12T08:08:31.824Z,2.824384,b9ff6c0,6 [FLog::Warning] Warning: HTTP error url:`https://apis.roblox.com/attribution/v1/events/post-authentication`
2024-10-12T08:08:31.824Z,2.824446,b9ff6c0,6 [FLog::Warning] Warning: HTTP error code:`nil`
2024-10-12T08:08:31.824Z,2.824487,b9ff6c0,6 [FLog::Warning] Warning: HTTP error body:`nil`
2024-10-12T08:08:31.996Z,2.996500,c3ff6c0,6 [FLog::Error] Asset (Image) "rbxthumb://type=AvatarHeadShot&id=-1&w=48&h=48&filters=circular" load failed in TextureManager::PreloadTexture: Request failed

### Roblox Experience link

-

**Comment by Floya-dev** [comment] 2024-10-12 09:47
I encountered the same issue lately. Fixed it by reinstalling Sober from flatpak. And when installing roblox apk for Sober, I chose the automatic install. That fixed the issue for me.

**Comment by tunis4** [comment] 2024-10-12 10:57
update sober

duplicate of #297

**Closed by tunis4** 2024-10-12 10:57 UTC
Labels: bug

**Comment by UnitieG** [comment] 2024-10-13 02:20
> update sober
> 
> duplicate of #297

:+1:
