### ISSUE TITLE
Unhandled SIGSEGV at rip 0x0000560a7a8ca320

### ISSUE THREAD

**Issue by Zash012** [vinegarhq/sober#13] opened 2024-08-03 17:17 UTC
I'm using debian and whenever i try to run sober (from both the terminal and from the apps menu) i get this error: Unhandled SIGSEGV at rip 0x0000560a7a8ca320. Before the error, sober does seem to try to run, gives some error messages and then crashes before it can even load a windows (here are the error messages it gives btw: [log @ Roblox]: 2024-08-03T17:13:33.513Z,14.513378,8e9626c0,6 [FLog::Error] Error: collate_byname<char>::collate_byname failed to construct for 
[log @ Roblox]: 2024-08-03T17:13:33.688Z,14.688690,8e9626c0,6 [FLog::SingleSurfaceApp] initializeLuaAppWithLoggedInUser: (stage:None).
[log @ Roblox]: 2024-08-03T17:13:33.690Z,14.690135,8e9626c0,6 [FLog::SingleSurfaceApp] applyLocale
)
Here are my locale settings:
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by apprehensions** [comment] 2024-08-03 19:12
Duplicate of #16

**Closed by apprehensions** 2024-08-03 19:12 UTC

**Comment by Zash012** [comment] 2024-08-03 19:14
fixed by running flatpak override --user --env=LC_ALL=en_US.UTF-8 org.vinegarhq.Sober
