### ISSUE TITLE
Broken pthread calls in certain games

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#74] opened 2024-08-08 23:44 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

sakura stand keeps crashing for some reason

### Roblox Experience link

https://www.roblox.com/games/8534845015/KAIJU-RED-MIST-Sakura-Stand

**Comment by Amgsdfyhadfgybi** [comment] 2024-08-11 13:55
?

**Comment by apprehensions** [comment] 2024-08-13 13:53
Duplicate of #103

**Closed by apprehensions** 2024-08-13 13:53 UTC
Labels: bug
