### ISSUE TITLE
Client crashing in Defusal

### ISSUE THREAD

**Issue by vovan2055** [vinegarhq/sober#270] opened 2024-10-01 19:22 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sober crashes mid-game when playing Defusal
[log.txt](https://github.com/user-attachments/files/17215288/log.txt)

### Roblox Experience link

https://www.roblox.com/games/3577061261/Defuse

**Comment by tunis4** [comment] 2024-10-01 19:27
duplicate of #258

**Closed by tunis4** 2024-10-01 19:27 UTC
Labels: bug
