### ISSUE TITLE
Issues using / to open the chat in quite a few games

### ISSUE THREAD

**Issue by XxsjrapsxX** [vinegarhq/sober#224] opened 2024-09-12 02:32 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have noticed that when attempting to press the / button to open the chat it does not seem to work which can be a little inconvenient when wanting to chat quickly, especially in pvp games.

**Comment by Hri7566** [comment] 2024-09-12 02:42
have you seen any games where it does work?

**Comment by XxsjrapsxX** [comment] 2024-09-12 03:27
not as of recently

**Comment by fuckindumbfox** [comment] 2024-09-12 18:28
i am also suffering from this bug.

**Comment by Yaco-Taco** [comment] 2024-09-12 20:06
same here

**Comment by XxsjrapsxX** [comment] 2024-09-12 22:45
is anyone here also having issues with getting shift lock to work well? It seems a lot of features that are existent on basic pc versions are missing when i comes to controls and actual settings in roblox.

**Comment by fuckindumbfox** [comment] 2024-09-13 23:34
> is anyone here also having issues with getting shift lock to work well? It seems a lot of features that are existent on basic pc versions are missing when i comes to controls and actual settings in roblox.

for some reason for me the shift lock toggle in settings is missing too, but shift lock itself works well for me

**Comment by JuniorBeats10** [comment] 2024-09-19 16:21
same here

**Comment by Naymmmm** [comment] 2024-09-22 03:03
This is an issue with LegacyChatService and is likely not a Sober issue. As an alternative you can press "." to open chat.

**Comment by Naymmmm** [comment] 2024-09-22 03:03
This is an issue with LegacyChatService and is likely not a Sober issue. As an alternative you can press "." to open chat.

**Comment by tunis4** [comment] 2024-10-01 13:28
duplicate of #254

**Closed by tunis4** 2024-10-01 13:28 UTC
Labels: bug
