### ISSUE TITLE
Roblox key not working to chat

### ISSUE THREAD

**Issue by Ghosty-siu** [vinegarhq/sober#231] opened 2024-09-14 10:27 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So there is this issue where i cant use the / key on any games with the old chat box. on blade ball, for example, the / key works since its using the new chat box.

**Comment by rosebytee** [comment] 2024-09-22 21:21
Found this also, would really like a fix since it's been driving me nuts.

**Comment by tunis4** [comment] 2024-10-01 13:28
duplicate of #254

**Closed by tunis4** 2024-10-01 13:28 UTC
Labels: bug
