### ISSUE TITLE
Servers no longer supported

### ISSUE THREAD

**Issue by wizenedatom5485** [vinegarhq/sober#301] opened 2024-10-11 01:35 UTC
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I launch any sort of expierience the software just crashes. I have noticed recent APK updates for the APK mirrors and I was wondering if you could maybe make it so Sober could support those new packages? I am a SteamOS user and if anyone else has a sollution respond please. :D

**Comment by skoove** [comment] 2024-10-11 07:33
duplicate issue

**Comment by apprehensions** [comment] 2024-10-11 07:33
Duplicate of #297

**Closed** 2024-10-11 07:33 UTC
Labels: bug
